landscapeMemberClasses: 
   - name: Steering Member
     category: Steering
   - name: General Member
     category: General
   - name: Contributor Member
     category: Contributor
slug: app-defense-alliance-fund
landscapeMemberCategory: Alliance Members
